#eureka:
#  instance:
#    prefer-ip-address: true
#    hostname: localhost 
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone : http://localhost:8761/eureka
spring:
  application:
    name: RATING-SERVICE
    
  config:
    import: configserver:http://localhost:9092
    
#okta 
okta:
  oauth2:
    issuer: https://dev-97326427.okta.com/oauth2/default
    audience: api://default